extends RefCounted
## 音效常量表（自动生成，勿手改）—— 由 scripts/gen_sfx_assets.py 从
## scripts/sfx_subsystem.json（逆向权威，续195）+ scripts/_decoded_kos/ 生成。
##
## 原版 `play_sfx(id)`（0x4997c0）用数字 id；本表以下标 = id 还原映射。
## ⚠️ 不用 class_name（无头模式不建类缓存），引用方 preload 本脚本。

const COUNT : int = 39

## 下标 = 音效 id → 原文件名（不含扩展名）
const NAMES : Array[String] = [
		"CLICK",
		"CANCEL",
		"KOUGEKI1",
		"KOUGEKI2",
		"OPENGATE",
		"TOTUGEKI",
		"TEPPOU",
		"IDOU",
		"SEIKOU",
		"SHIPPAI",
		"GIHEI",
		"KAKEI",
		"RAKUSEKI",
		"SYUUZEN",
		"UMETATE",
		"ZANSYU",
		"SHIKI",
		"KOATARI",
		"OOATARI",
		"UKETA",
		"YOKETA",
		"METUBUSI",
		"IATSU",
		"KEMURI",
		"NIGERU",
		"IKARI",
		"KAISHIN",
		"TGENSYOU",
		"IGENSYOU",
		"INOTIGOI",
		"IZOUKA",
		"GINOUUP",
		"MACHIMES",
		"NINJA",
		"MI_HARE",
		"MI_AME",
		"MATISIRO",
		"SIKAKU",
		"KAMINARI"
]

## 下标 = 音效 id → 中文语义
const ZH : Array[String] = [
		"UI 点击/确定",
		"UI 取消",
		"攻击(通常)1",
		"攻击(通常)2",
		"开城门",
		"突击",
		"铁炮射击",
		"部队移动",
		"行动成功",
		"行动失败",
		"伪兵(疑兵)计略",
		"火计(火攻)",
		"落石(攻城防御)",
		"修缮(修复)",
		"埋立(填埋/普请)",
		"残守/残兵(待考)",
		"士气(动摇/鼓舞)",
		"小命中(轻伤)",
		"大命中(重创)",
		"受击(挨打)",
		"闪避(躲开)",
		"目溃(致盲)",
		"威压",
		"烟(烟幕)",
		"败走/逃跑",
		"愤怒",
		"会心一击",
		"敌现象/敌现身",
		"异现象(异变)",
		"命乞(求饶)",
		"威吓/伊杂贺(待考)",
		"技能提升",
		"町消息(町内广播)",
		"忍者",
		"天候·晴",
		"天候·雨",
		"待机/町城(待考)",
		"死角(背袭)",
		"雷"
]

## 下标 = 音效 id → 类别（UI / 战斗 / 内政 …）
const CATS : Array[String] = [
		"UI",
		"UI",
		"战斗",
		"战斗",
		"攻城战",
		"战斗",
		"战斗",
		"战斗",
		"内政/通用",
		"内政/通用",
		"计略",
		"计略",
		"攻城战",
		"攻城战/内政",
		"攻城战/内政",
		"战斗",
		"战斗",
		"单挑/战斗",
		"单挑/战斗",
		"单挑/战斗",
		"单挑/战斗",
		"忍术/计略",
		"计略",
		"计略",
		"战斗",
		"战斗",
		"单挑/战斗",
		"战斗",
		"战斗/事件",
		"单挑/战斗",
		"计略",
		"养成",
		"内政",
		"忍术/计略",
		"天候",
		"天候",
		"内政",
		"战斗",
		"天候/计略"
]

## 下标 = 音效 id → 资产路径（res://）
const PATHS : Array[String] = [
		"res://assets/audio/sfx/CLICK.wav",
		"res://assets/audio/sfx/CANCEL.wav",
		"res://assets/audio/sfx/KOUGEKI1.wav",
		"res://assets/audio/sfx/KOUGEKI2.wav",
		"res://assets/audio/sfx/OPENGATE.wav",
		"res://assets/audio/sfx/TOTUGEKI.wav",
		"res://assets/audio/sfx/TEPPOU.wav",
		"res://assets/audio/sfx/IDOU.wav",
		"res://assets/audio/sfx/SEIKOU.wav",
		"res://assets/audio/sfx/SHIPPAI.wav",
		"res://assets/audio/sfx/GIHEI.wav",
		"res://assets/audio/sfx/KAKEI.wav",
		"res://assets/audio/sfx/RAKUSEKI.wav",
		"res://assets/audio/sfx/SYUUZEN.wav",
		"res://assets/audio/sfx/UMETATE.wav",
		"res://assets/audio/sfx/ZANSYU.wav",
		"res://assets/audio/sfx/SHIKI.wav",
		"res://assets/audio/sfx/KOATARI.wav",
		"res://assets/audio/sfx/OOATARI.wav",
		"res://assets/audio/sfx/UKETA.wav",
		"res://assets/audio/sfx/YOKETA.wav",
		"res://assets/audio/sfx/METUBUSI.wav",
		"res://assets/audio/sfx/IATSU.wav",
		"res://assets/audio/sfx/KEMURI.wav",
		"res://assets/audio/sfx/NIGERU.wav",
		"res://assets/audio/sfx/IKARI.wav",
		"res://assets/audio/sfx/KAISHIN.wav",
		"res://assets/audio/sfx/TGENSYOU.wav",
		"res://assets/audio/sfx/IGENSYOU.wav",
		"res://assets/audio/sfx/INOTIGOI.wav",
		"res://assets/audio/sfx/IZOUKA.wav",
		"res://assets/audio/sfx/GINOUUP.wav",
		"res://assets/audio/sfx/MACHIMES.wav",
		"res://assets/audio/sfx/NINJA.wav",
		"res://assets/audio/sfx/MI_HARE.wav",
		"res://assets/audio/sfx/MI_AME.wav",
		"res://assets/audio/sfx/MATISIRO.wav",
		"res://assets/audio/sfx/SIKAKU.wav",
		"res://assets/audio/sfx/KAMINARI.wav"
]

## 原版判定为「死资源」的 id（无任何调用点，续248）—— 资产存在但原版从不播放
const DEAD_IDS : Array = [15, 36]
